# Generated by Django 4.2.4 on 2024-02-13 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Сurrency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Дата')),
                ('char_code', models.CharField(max_length=3, verbose_name='Код')),
                ('name', models.CharField(max_length=200, verbose_name='Название')),
                ('value', models.DecimalField(decimal_places=3, max_digits=5, verbose_name='Курс')),
            ],
            options={
                'verbose_name': 'Валюта',
                'verbose_name_plural': 'Валюты',
                'ordering': ['-date'],
                'indexes': [models.Index(fields=['char_code'], name='currency_to_char_co_97a815_idx'), models.Index(fields=['date'], name='currency_to_date_30b7fe_idx')],
            },
        ),
    ]
